import './globals.css'
import Providers from '@/store/Providers'
import NavbarPublic from '@/components/Navbar/NavbarPublic'


export const metadata = {
  title: 'Hunting Redux',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='w-full min-h-screen flex flex-col'>
        <Providers>
          <NavbarPublic />
        {children}
        </Providers>
        </body>
    </html>
  )
}
